GET http://localhost:3002

###

POST http://localhost:3002/register
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "asdf@asdf.asdf",
    "password": "123456"

}
###

PUT http://localhost:3002/users/50
Content-Type: application/json

{
    "firstName": "Vanessa",
    "lastName": "Doe",
    "age":35
}
###

DELETE  http://localhost:3002/users/50
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "age":35
}